### ISSUE TITLE
쫌 중요한 이슈

### ISSUE THREAD

**Issue by pmh-only** [KataLin177/SovietPlayer#3]
![image](https://user-images.githubusercontent.com/39158228/82009178-9d3ecf00-96a9-11ea-92e8-6f88bbb586e0.png)
.vbproj 파일이 시공가서 컴파일을 못하는데요!

**Comment by pmh-only** [comment]
아 참고로 개인정보나 파일 경로 가리려고 한거면 이미 다른파일에 적혀져있어요
https://github.com/KataLin177/SovietPlayer/blob/0171a7c70804b4d0ae6e74ffbe5a80a4eac56dcf/SovietPlayer/obj/Debug/SovietPlayer.vbproj.FileListAbsolute.txt#L1-L18

**Comment by KataLin177** [comment]
1. 컴파일 안 하셔도 https://github.com/KataLin177/SovietPlayer/releases 에 파일 있습니다
Wine 써서 돌리세요 (?)

2. 파일 경로 가릴 생각도 없었...

**Comment by pmh-only** [comment]
아! 릴리즈가 있었군요! 눈이 썩었나 봅니다!
